//This file was created via CT-GUI! Editing it is not advised!
//Don't touch me!
//#Remove
recipes.remove(<thermalfoundation:material:163>);
recipes.removeShapeless(<thermalfoundation:material:163>, []);
recipes.removeShapeless(<forestry:ingot_bronze>, []);
recipes.remove(<icbmclassic:clump>);
recipes.remove(<icbmclassic:laserdetonator>);
recipes.remove(<icbmclassic:rocketlauncher>);
recipes.remove(<icbmclassic:radarstation>);
recipes.remove(<icbmclassic:emptower>);
recipes.remove(<icbmclassic:antidote>);
recipes.remove(<icbmclassic:tracker>);
recipes.remove(<icbmclassic:defuser>);
recipes.remove(<icbmclassic:radargun>);
recipes.remove(<icbmclassic:remotedetonator>);
recipes.remove(<icbmclassic:laserdetonator>);
recipes.remove(<icbmclassic:rocketlauncher>);
recipes.remove(<icbmclassic:radarstation>);
recipes.remove(<icbmclassic:emptower>);
recipes.remove(<icbmclassic:launcherbase:0>);
recipes.remove(<icbmclassic:launcherframe:0>);
recipes.remove(<icbmclassic:launcherbase:1>);
recipes.remove(<icbmclassic:launcherframe:1>);
recipes.remove(<icbmclassic:launcherbase:2>);
recipes.remove(<icbmclassic:launcherframe:2>);
recipes.remove(<icbmclassic:circuit>);
recipes.remove(<icbmclassic:circuit:1>);
recipes.remove(<icbmclassic:circuit:2>);
recipes.remove(<icbmclassic:launcherscreen>);
recipes.remove(<icbmclassic:launcherscreen:1>);
recipes.remove(<icbmclassic:launcherscreen:2>);
recipes.remove(<icbmclassic:missile:24>);
recipes.remove(<icbmclassic:cruiselauncher>);
recipes.remove(<icbmclassic:poisonpowder>);
recipes.remove(<icbmclassic:explosives:0>);
recipes.remove(<icbmclassic:explosives:22>);
recipes.remove(<icbmclassic:explosives:21>);
recipes.remove(<icbmclassic:explosives:10>);
recipes.remove(<icbmclassic:explosives:18>);
recipes.remove(<icbmclassic:explosives:17>);
recipes.remove(<icbmclassic:explosives:10>);
recipes.remove(<icbmclassic:explosives:6>);
recipes.remove(<icbmclassic:explosives:8>);
recipes.remove(<icbmclassic:explosives:7>);
recipes.remove(<icbmclassic:explosives:8>);
recipes.remove(<icbmclassic:explosives:9>);
recipes.remove(<icbmclassic:explosives:2>);
recipes.remove(<icbmclassic:explosives:1>);
recipes.remove(<icbmclassic:explosives:3>);
recipes.remove(<icbmclassic:explosives:4>);
recipes.remove(<icbmclassic:explosives:23>);
recipes.remove(<icbmclassic:explosives:19>);
recipes.remove(<icbmclassic:explosives:12>);
recipes.remove(<icbmclassic:explosives:15>);
recipes.remove(<icbmclassic:explosives:5>);
recipes.remove(<icbmclassic:wire>);
recipes.remove(<icbmclassic:wire:1>);
recipes.remove(<icbmclassic:battery>);
recipes.remove(<icbmclassic:grenade:*>);
recipes.removeShapeless(<thermalfoundation:material:32>, []);
recipes.removeShapeless(<thermalfoundation:material:355>, []);
recipes.removeShapeless(<thermalfoundation:material:321>, []);
recipes.removeShapeless(<thermalfoundation:material:323>, []);
recipes.removeShapeless(<thermalfoundation:material:33>, []);
recipes.removeShapeless(<thermalfoundation:material:320>, []);
recipes.removeShapeless(<thermalfoundation:material:*>, []);
recipes.remove(<xnet:antenna>);
recipes.remove(<xnet:antenna_base>);
recipes.remove(<xnet:wireless_router>);
recipes.remove(<xnet:router>);
recipes.remove(<xnet:controller>);
recipes.remove(<xnet:redstone_proxy>);
recipes.remove(<xnet:advanced_connector>);
recipes.remove(<xnet:connector>);
recipes.remove(<xnet:connector:4>);
recipes.remove(<xnet:connector_upgrade>);
recipes.remove(<xnet:netcable:4>);
recipes.remove(<xnet:netcable>);
recipes.remove(<xnet:antenna_dish>);
recipes.removeShaped(<ore:plateLead>, [[<ore:ingotLead>, <ic2:forge_hammer>, null],[null, null, null], [null, null, null]]);
recipes.removeShaped(<ore:plateBronze>, [[<ore:ingotBronze>, <ic2:forge_hammer>, null],[null, null, null], [null, null, null]]);
recipes.removeShaped(<ore:plateSilver>, [[<ore:ingotSilver>, <ic2:forge_hammer>, null],[null, null, null], [null, null, null]]);
recipes.removeShaped(<ore:plateTin>, [[<ore:ingotTin>, <ic2:forge_hammer>, null],[null, null, null], [null, null, null]]);
recipes.removeShaped(<ore:plateCopper>, [[<ore:ingotCopper>, <ic2:forge_hammer>, null],[null, null, null], [null, null, null]]);
recipes.removeShaped(<ore:plateIron>, [[<ore:ingotIron>, <ic2:forge_hammer>, null],[null, null, null], [null, null, null]]);
recipes.removeShaped(<ore:plateGold>, [[<ore:ingotGold>, <ic2:forge_hammer>, null],[null, null, null], [null, null, null]]);
recipes.remove(<rockhounding_chemistry:misc_items:22>);
recipes.remove(<rockhounding_chemistry:misc_items:10>);
recipes.remove(<rockhounding_chemistry:misc_items:1>);
recipes.remove(<rockhounding_chemistry:misc_items:21>);
recipes.remove(<thermalfoundation:material:32>);
recipes.remove(<thermalfoundation:material:321>);
recipes.remove(<thermalfoundation:material:323>);
recipes.remove(<thermalfoundation:material:355>);
recipes.remove(<thermalfoundation:material:320>);
recipes.remove(<ic2:misc_resource:1>);
recipes.remove(<ic2:crafting:13>);
recipes.remove(<ic2:te:2>);
recipes.remove(<draconicevolution:energy_crystal>);
recipes.remove(<draconicevolution:energy_crystal:1>);
recipes.remove(<draconicevolution:wyvern_energy_core>);
recipes.remove(<draconicevolution:wyvern_core>);
recipes.remove(<draconicevolution:draconic_core>);
recipes.remove(<xat:fairy_ring>);
recipes.remove(<thaumcraft:plate:1>);
recipes.remove(<immersiveengineering:metal:38>);
recipes.remove(<immersiveengineering:metal:37>);
recipes.remove(<immersiveengineering:metal:36>);
recipes.remove(<immersiveengineering:metal:35>);
recipes.remove(<immersiveengineering:metal:35>);
recipes.remove(<immersiveengineering:metal:34>);
recipes.remove(<immersiveengineering:metal:33>);
recipes.remove(<immersiveengineering:metal:32>);
recipes.remove(<immersiveengineering:metal:31>);
recipes.remove(<immersiveengineering:metal:30>);
recipes.remove(<immersiveengineering:metal:40>);
recipes.remove(<immersiveengineering:metal:39>);
recipes.remove(<spartanweaponry:pike_lead>);
recipes.remove(<spartanweaponry:halberd_lead>);
recipes.remove(<spartanweaponry:spear_lead>);
recipes.remove(<spartanweaponry:greatsword_lead>);
recipes.remove(<spartanweaponry:rapier_lead>);
recipes.remove(<spartanweaponry:saber_lead>);
recipes.remove(<spartanweaponry:katana_lead>);
recipes.remove(<spartanweaponry:longsword_lead>);
recipes.remove(<spartanweaponry:dagger_lead>);
recipes.remove(<spartanweaponry:glaive_lead>);
recipes.remove(<spartanweaponry:glaive_lead>);
recipes.remove(<spartanweaponry:battleaxe_lead>);
recipes.remove(<spartanweaponry:boomerang_lead>);
recipes.remove(<spartanweaponry:javelin_lead>);
recipes.remove(<spartanweaponry:throwing_axe_lead>);
recipes.remove(<spartanweaponry:throwing_knife_lead>);
recipes.remove(<spartanweaponry:crossbow_lead>);
recipes.remove(<spartanweaponry:longbow_lead>);
recipes.remove(<spartanweaponry:lance_lead>);
recipes.remove(<minecraft:wooden_pickaxe>);
recipes.remove(<opencomputers:material:6>);
recipes.remove(<opencomputers:material:12>);
recipes.remove(<xat:polarized_stone>);
//Don't touch me!
//#Add=reskillable:attack|14,reskillable:defence|14,reskillable:building|24
recipes.addShaped(<icbmclassic:missile:24>, [[<forestry:can:1>.withTag({Fluid: {FluidName: "liquid_oxygen", Amount: 1000}}).onlyWithTag({Fluid: {FluidName: "liquid_oxygen", Amount: 1000}}), <rockhounding_chemistry:alloy_parts:91>, <forestry:can:1>.withTag({Fluid: {FluidName: "ic2hydrogen", Amount: 1000}}).onlyWithTag({Fluid: {FluidName: "ic2hydrogen", Amount: 1000}})],[<ic2:crafting:34>, <opencomputers:component:14>, <ic2:crafting:34>], [<ic2:rsh_condensator>.withTag({advDmg: 0}).onlyWithTag({advDmg: 0}), <ic2:jetpack:1>.withTag({Quality: {}, Fluid: {FluidName: "ic2biogas", Amount: 30000}}).onlyWithTag({Quality: {}, Fluid: {FluidName: "ic2biogas", Amount: 30000}}), <rockhounding_chemistry:alloy_parts:79>]]);
recipes.addShaped(<icbmclassic:antidote> * 8, [[<minecraft:red_flower>, <minecraft:milk_bucket>, null],[<minecraft:potion>.withTag({Potion: "minecraft:healing"}).onlyWithTag({Potion: "minecraft:healing"}), <rockhounding_chemistry:chemical_dusts:23>, null], [null, null, null]]);
recipes.addShaped(<icbmclassic:explosives:3> * 2, [[null, null, null],[<forestry:can:1>.withTag({Fluid: {FluidName: "toxic_waste", Amount: 1000}}).onlyWithTag({Fluid: {FluidName: "toxic_waste", Amount: 1000}}), <icbmclassic:explosives>, <forestry:can:1>.withTag({Fluid: {FluidName: "toxic_waste", Amount: 1000}}).onlyWithTag({Fluid: {FluidName: "toxic_waste", Amount: 1000}})], [<icbmclassic:poisonpowder>, <icbmclassic:poisonpowder>, <icbmclassic:poisonpowder>]]);
recipes.addShaped(<icbmclassic:explosives:4> * 2, [[null, null, null],[<forestry:can:1>.withTag({Fluid: {FluidName: "nitric_acid", Amount: 1000}}).onlyWithTag({Fluid: {FluidName: "nitric_acid", Amount: 1000}}), <icbmclassic:explosives>, <forestry:can:1>.withTag({Fluid: {FluidName: "sulfuric_acid", Amount: 1000}}).onlyWithTag({Fluid: {FluidName: "sulfuric_acid", Amount: 1000}})], [<icbmclassic:poisonpowder>, <icbmclassic:poisonpowder>, <icbmclassic:poisonpowder>]]);
recipes.addShaped(<icbmclassic:explosives:18>, [[null, <ic2:misc_resource:1>, null],[<avaritia:resource:1>, <icbmclassic:explosives:13>, <avaritia:resource:1>], [<thaumcraft:phial:1>.withTag({Aspects: [{amount: 10, key: "aqua"}]}).onlyWithTag({Aspects: [{amount: 10, key: "aqua"}]}), <thaumcraft:phial:1>.withTag({Aspects: [{amount: 10, key: "aqua"}]}).onlyWithTag({Aspects: [{amount: 10, key: "aqua"}]}), <thaumcraft:phial:1>.withTag({Aspects: [{amount: 10, key: "aqua"}]}).onlyWithTag({Aspects: [{amount: 10, key: "aqua"}]})]]);
recipes.addShaped(<icbmclassic:explosives:17>, [[null, <ic2:misc_resource:1>, null],[<avaritia:resource:1>, <icbmclassic:explosives:13>, <avaritia:resource:1>], [<thaumcraft:phial:1>.withTag({Aspects: [{amount: 10, key: "ignis"}]}).onlyWithTag({Aspects: [{amount: 10, key: "ignis"}]}), <thaumcraft:phial:1>.withTag({Aspects: [{amount: 10, key: "ignis"}]}).onlyWithTag({Aspects: [{amount: 10, key: "ignis"}]}), <thaumcraft:phial:1>.withTag({Aspects: [{amount: 10, key: "ignis"}]}).onlyWithTag({Aspects: [{amount: 10, key: "ignis"}]})]]);
recipes.addShaped(<icbmclassic:launcherscreen>, [[<appliedenergistics2:part:16>, null, null],[<opencomputers:material:7>, <opencomputers:component:13>, <appliedenergistics2:part:200>], [<ic2:te:72>, <ore:plateSteel>, <ore:plateSteel>]]);
recipes.addShaped(<icbmclassic:launcherscreen:1>, [[<appliedenergistics2:part:56>, null, null],[<opencomputers:material:8>, <opencomputers:component:14>, <appliedenergistics2:part:180>], [<ic2:te:74>, <ore:plateSteel>, <ore:plateSteel>]]);
recipes.addShaped(<icbmclassic:launcherscreen:2>, [[<appliedenergistics2:part:76>, null, null],[<opencomputers:material:9>, <opencomputers:component:15>, <appliedenergistics2:part:160>], [<ic2:te:75>, <ore:plateSteel>, <ore:plateSteel>]]);
recipes.addShaped(<icbmclassic:remotedetonator>, [[null, <xnet:antenna>, null],[<immersiveengineering:toolupgrade:6>, <opencomputers:material:7>, <ore:plateAluminum>], [<ore:plateAluminum>, <ic2:re_battery:26>, <ore:plateAluminum>]]);
recipes.addShaped(<icbmclassic:laserdetonator>, [[<ore:plateAluminum>, <ore:plateAluminum>, null],[<immersiveengineering:toolupgrade:6>, <opencomputers:component:13>, <rockhounding_chemistry:alloy_items_gems:1>], [<ic2:re_battery:26>, <ic2:re_battery:26>, null]]);
recipes.addShaped(<icbmclassic:tracker>, [[null, <xnet:antenna>, null],[<opencomputers:material:7>, <opencomputers:component:13>, <appliedenergistics2:material:42>], [<ore:plateAluminum>, <immersiveengineering:toolupgrade:6>, <ore:plateAluminum>]]);
recipes.addShaped(<icbmclassic:emptower>, [[null, <immersiveengineering:metal_device1:8>, null],[<ic2:cable:3>, <immersiveengineering:metal_decoration0>, <opencomputers:material:9>], [<ore:plateSteel>, <ic2:te:75>, <ore:plateSteel>]]);
recipes.addShaped(<icbmclassic:radarstation>, [[<ic2:frequency_transmitter>, <xnet:antenna_dish>, null],[<ic2:te:74>, <opencomputers:component:15>, <icbmclassic:radargun>], [<ore:plateAluminum>, <ore:plateAluminum>, <ore:plateAluminum>]]);
recipes.addShaped(<icbmclassic:radargun>, [[<ic2:re_battery:26>, <ore:plateAluminum>, null],[<ic2:frequency_transmitter>, <appliedenergistics2:material:42>, <xnet:antenna_dish>], [<immersiveengineering:metal_decoration0>, <ore:plateAluminum>, null]]);
recipes.addShaped(<icbmclassic:cruiselauncher>, [[<icbmclassic:launcherbase:2>, <icbmclassic:launcherframe:2>, <icbmclassic:launcherscreen:2>],[null, <ic2:te:16>, <ic2:re_battery:26>], [<rockhounding_chemistry:alloy_parts:40>, <ic2:te:16>, <rockhounding_chemistry:alloy_parts:40>]]);
recipes.addShaped(<icbmclassic:explosives:22>, [[<ic2:iridium_reflector>, <astralsorcery:itemperkgem:2>, <ic2:iridium_reflector>],[<icbmclassic:explosives:18>, <avaritia:block_resource>, <icbmclassic:explosives:17>], [<ic2:iridium_reflector>, <avaritia:resource:5>, <ic2:iridium_reflector>]]);
recipes.addShaped(<icbmclassic:explosives:9>, [[null, <icbmclassic:explosives:3>, null],[<icbmclassic:explosives:6>, <thaumcraft:brain>, <icbmclassic:explosives:6>], [null, <icbmclassic:explosives:4>, null]]);
recipes.addShaped(<icbmclassic:explosives:21>, [[null, <ic2:te:74>, null],[<icbmclassic:explosives:10>, <immersiveengineering:metal_decoration0:2>, <icbmclassic:explosives:10>], [null, <ic2:te:74>, null]]);
recipes.addShaped(<icbmclassic:explosives:10>, [[<minecraft:noteblock>, <immersiveengineering:metal_decoration0:1>, <minecraft:noteblock>],[<minecraft:noteblock>, <rockhounding_chemistry:misc_items:26>, <minecraft:noteblock>], [<icbmclassic:explosives:6>, <ic2:te:74>, <icbmclassic:explosives:6>]]);
recipes.addShaped(<icbmclassic:explosives:8>, [[<rockhounding_chemistry:alloy_items_deco:2>, <crossroads:sulfur:*>, <rockhounding_chemistry:alloy_items_deco:2>],[<icbmclassic:explosives:1>, <icbmclassic:explosives:2>, <icbmclassic:explosives:1>], [<rockhounding_chemistry:alloy_items_deco:2>, <crossroads:sulfur>, <rockhounding_chemistry:alloy_items_deco:2>]]);
recipes.addShaped(<icbmclassic:explosives:7>, [[null, <astralsorcery:itemcelestialcrystal:*>, null],[null, <icbmclassic:explosives>, null], [null, null, null]]);
recipes.addShaped(<icbmclassic:explosives:6>, [[null, <astralsorcery:itemrockcrystalsimple:*>, null],[null, <icbmclassic:explosives>, null], [null, null, null]]);
recipes.addShaped(<icbmclassic:explosives:2>, [[<ore:dustIron>, <icbmclassic:explosives>, null],[<ore:dustIron>, <icbmclassic:explosives>, <ore:dustAluminum>], [<ore:dustIron>, <icbmclassic:explosives>, <minecraft:lava_bucket>]]);
recipes.addShaped(<icbmclassic:explosives:1>, [[null, <rockhounding_chemistry:alloy_parts:49>, null],[<rockhounding_chemistry:alloy_parts:49>, <icbmclassic:explosives>, <rockhounding_chemistry:alloy_parts:49>], [null, <rockhounding_chemistry:alloy_parts:49>, null]]);
recipes.addShaped(<icbmclassic:explosives> * 2, [[<minecraft:tnt>, <minecraft:tnt>, <minecraft:tnt>],[<minecraft:tnt>, <minecraft:tnt>, <minecraft:tnt>], [<ore:plateSteel>, <opencomputers:material:7>, <ore:plateSteel>]]);
recipes.addShaped(<icbmclassic:launcherbase:2>, [[<opencomputers:material:9>, <minecraft:dye:6>, <opencomputers:material:9>],[<icbmclassic:launcherframe:2>, <icbmclassic:launcherbase:1>, <icbmclassic:launcherframe:2>], [<rockhounding_chemistry:alloy_parts:1>, <rockhounding_chemistry:alloy_parts:79>, <rockhounding_chemistry:alloy_parts:1>]]);
recipes.addShaped(<icbmclassic:launcherbase:1>, [[<opencomputers:material:8>, <minecraft:dye:1>, <opencomputers:material:8>],[<icbmclassic:launcherframe:1>, <icbmclassic:launcherbase>, <icbmclassic:launcherframe:1>], [<ic2:te:16>, <rockhounding_chemistry:alloy_parts:88>, <ic2:te:16>]]);
recipes.addShaped(<icbmclassic:launcherbase:1>, [[<opencomputers:material:8>, <minecraft:dye:1>, <opencomputers:material:8>],[<icbmclassic:launcherframe:1>, <icbmclassic:launcherbase>, <icbmclassic:launcherframe:1>], [<ic2:te:16>, <rockhounding_chemistry:alloy_parts:46>, <ic2:te:16>]]);
recipes.addShaped(<icbmclassic:launcherbase>, [[null, <minecraft:dye:2>, null],[<icbmclassic:launcherframe>, <opencomputers:material:7>, <icbmclassic:launcherframe>], [<ic2:te:16>, <rockhounding_chemistry:alloy_parts:88>, <ic2:te:16>]]);
recipes.addShaped(<icbmclassic:launcherframe:2>, [[<immersiveengineering:material:2>, null, <immersiveengineering:material:2>],[<rockhounding_chemistry:alloy_parts:1>, <icbmclassic:launcherframe:1>, <rockhounding_chemistry:alloy_parts:1>], [<immersiveengineering:material:2>, <rockhounding_chemistry:alloy_parts:91>, <immersiveengineering:material:2>]]);
recipes.addShaped(<icbmclassic:launcherframe:1>, [[<immersiveengineering:material:2>, <immersiveengineering:material:2>, null],[<immersiveengineering:metal_decoration2>, <immersiveengineering:metal_decoration2>, null], [<immersiveengineering:metal_decoration1:1>, <immersiveengineering:metal_decoration1:1>, null]]);
recipes.addShaped(<icbmclassic:launcherframe>, [[<immersiveengineering:metal_decoration2:2>, <immersiveengineering:metal_decoration2:2>, null],[<immersiveengineering:material:3>, <immersiveengineering:material:3>, null], [<immersiveengineering:metal_decoration1:5>, <immersiveengineering:metal_decoration1:5>, null]]);
recipes.addShaped(<ic2:cable>.withTag({type: 0 as byte, insulation: 0 as byte}) * 2, [[null, null, null],[<ore:wireCopper>, <ore:wireCopper>, <ore:wireCopper>], [null, null, null]]);
recipes.addShaped(<xnet:netcable:4>.withTag({display: {LocName: "tile.xnet.netcable_routing.name"}}) * 4, [[null, <ic2:cable>.withTag({type: 0 as byte, insulation: 0 as byte}).onlyWithTag({type: 0 as byte, insulation: 0 as byte}), null],[<minecraft:redstone>, <xnet:netcable>.withTag({display: {LocName: "tile.xnet.netcable_blue.name"}}).onlyWithTag({display: {LocName: "tile.xnet.netcable_blue.name"}}), <minecraft:redstone>], [null, <ic2:cable>.withTag({type: 0 as byte, insulation: 0 as byte}).onlyWithTag({type: 0 as byte, insulation: 0 as byte}), null]]);
recipes.addShaped(<xnet:netcable:0>.withTag({display: {LocName: "tile.xnet.netcable_blue.name"}}) * 8, [[null, <minecraft:iron_ingot>, null],[<ic2:cable>.withTag({type: 0 as byte, insulation: 0 as byte}).onlyWithTag({type: 0 as byte, insulation: 0 as byte}), <essentials:item_chute>, <ic2:cable>.withTag({type: 0 as byte, insulation: 0 as byte}).onlyWithTag({type: 0 as byte, insulation: 0 as byte})], [null, <minecraft:iron_ingot>, null]]);
recipes.addShaped(<xnet:antenna_dish>, [[<appliedenergistics2:material:9>, null, <ic2:crafting:3>],[<ic2:crafting:3>, <immersiveengineering:material:2>, <ic2:crafting:3>], [null, <immersiveengineering:metal_decoration1>, null]]);
recipes.addShaped(<xnet:antenna>, [[<immersiveengineering:material:2>, <immersiveengineering:material:2>, <immersiveengineering:material:2>],[<immersiveengineering:material:2>, <immersiveengineering:material:2>, <immersiveengineering:material:2>], [null, <immersiveengineering:metal_decoration1>, null]]);
recipes.addShaped(<xnet:antenna_base>, [[null, <immersiveengineering:material:2>, null],[null, <immersiveengineering:material:2>, null], [null, <immersiveengineering:metal_decoration1>, null]]);
recipes.addShaped(<xnet:wireless_router>, [[<appliedenergistics2:material:9>, <appliedenergistics2:material:9>, <appliedenergistics2:material:9>],[<ic2:crafting:5>, <ic2:casing:5>, <ic2:crafting:5>], [<ic2:energy_crystal:26>, <minecraft:ender_pearl>, <ic2:energy_crystal:26>]]);
recipes.addShaped(<xnet:router>, [[<ic2:crafting:2>, <opencomputers:material:4>, <ic2:crafting:2>],[<ic2:crafting:6>, <ic2:casing:5>, <ic2:crafting:5>], [<ic2:crafting:3>, <minecraft:ender_pearl>, <ic2:crafting:3>]]);
recipes.addShaped(<xnet:controller>, [[<ic2:re_battery:26>, <ic2:crafting:2>, <ic2:crafting:5>],[<ic2:cable>.withTag({type: 0 as byte, insulation: 0 as byte}).onlyWithTag({type: 0 as byte, insulation: 0 as byte}), <ic2:casing:5>, <ic2:cable>.withTag({type: 0 as byte, insulation: 0 as byte}).onlyWithTag({type: 0 as byte, insulation: 0 as byte})], [<ic2:casing:3>, <opencomputers:material:7>, <ic2:casing:3>]]);
recipes.addShaped(<xnet:redstone_proxy>, [[<ic2:casing:3>, <minecraft:redstone>, <ic2:casing:3>],[<minecraft:redstone>, <immersiveengineering:material:8>, <minecraft:redstone>], [<ic2:casing:3>, <minecraft:redstone>, <ic2:casing:3>]]);
recipes.addShaped(<xnet:advanced_connector>, [[null, null, null],[<minecraft:ender_pearl>, <xnet:connector>, null], [<ic2:crafting:2>, <ic2:cable>.withTag({type: 0 as byte, insulation: 0 as byte}).onlyWithTag({type: 0 as byte, insulation: 0 as byte}), null]]);
recipes.addShaped(<xnet:connector:4>, [[null, <ic2:crafting:5>, null],[<minecraft:iron_ingot>, <xnet:connector>, <minecraft:iron_ingot>], [<minecraft:iron_ingot>, <ic2:re_battery:26>, <minecraft:iron_ingot>]]);
recipes.addShaped(<xnet:connector>, [[null, <immersiveengineering:material:8>, null],[<ic2:cable>.withTag({type: 0 as byte, insulation: 0 as byte}).onlyWithTag({type: 0 as byte, insulation: 0 as byte}), <ic2:casing:5>, <ic2:cable>.withTag({type: 0 as byte, insulation: 0 as byte}).onlyWithTag({type: 0 as byte, insulation: 0 as byte})], [<minecraft:redstone>, <ic2:crafting:6>, <minecraft:redstone>]]);
recipes.addShaped(<xnet:connector_upgrade>, [[null, <minecraft:ender_pearl>, null],[null, <immersiveengineering:material:8>, null], [null, <opencomputers:material:7>, null]]);
recipes.addShaped(<rockhounding_chemistry:misc_items:22>, [[<rockhounding_chemistry:misc_items:3>, <immersiveengineering:wirecoil>, <rockhounding_chemistry:misc_items:3>],[<immersiveengineering:metal_decoration0>, null, <immersiveengineering:metal_decoration0>], [<rockhounding_chemistry:misc_items:3>, <immersiveengineering:wirecoil>, <rockhounding_chemistry:misc_items:3>]]);
recipes.addShaped(<rockhounding_chemistry:misc_items:10>, [[<ore:dustTin>, <appliedenergistics2:material:20>, <ore:dustTin>],[<minecraft:gold_nugget>, <opencomputers:material:9>, <minecraft:gold_nugget>], [<minecraft:redstone>, <appliedenergistics2:material:5>, <minecraft:redstone>]]);
recipes.addShaped(<rockhounding_chemistry:misc_items:1>, [[<minecraft:redstone>, <ore:dustTin>, <minecraft:redstone>],[null, <opencomputers:material:8>, null], [<minecraft:gold_nugget>, <appliedenergistics2:material:5>, <minecraft:gold_nugget>]]);
recipes.addShaped(<rockhounding_chemistry:misc_items:21>, [[null, <immersiveengineering:wirecoil>, null],[<rockhounding_chemistry:misc_items:9>, <rockhounding_chemistry:misc_items:2>, <thermalfoundation:material:24>], [null, <immersiveengineering:wirecoil>, null]]);
recipes.addShaped(<ic2:crafting:13>, [[<rockhounding_chemistry:chemical_dusts:24>, <rockhounding_chemistry:chemical_dusts:24>, <rockhounding_chemistry:chemical_dusts:24>],[<rockhounding_chemistry:chemical_dusts:24>, <rockhounding_chemistry:chemical_dusts:24>, <rockhounding_chemistry:chemical_dusts:24>], [null, null, null]]);
recipes.addShaped(<opencomputers:material:12> * 3, [[<ore:dustAluminum>, <ore:dustAluminum>, <ore:dustAluminum>],[<appliedenergistics2:material:5>, <appliedenergistics2:material:5>, <appliedenergistics2:material:5>], [<minecraft:redstone>, <minecraft:redstone>, <minecraft:redstone>]]);
recipes.addShaped(<opencomputers:material:12>, [[null, <ore:dustAluminum>, null],[null, <appliedenergistics2:material:5>, null], [null, <minecraft:redstone>, null]]);
recipes.addShaped(<draconicevolution:energy_crystal> * 4, [[null, <minecraft:diamond>, null],[<minecraft:diamond>, <minecraft:diamond>, <minecraft:diamond>], [<draconicevolution:draconic_core>, <rockhounding_chemistry:alloy_items_gems:7>, <draconicevolution:draconic_core>]]);
recipes.addShaped(<draconicevolution:energy_crystal:1> * 4, [[<draconicevolution:wyvern_energy_core>, <draconicevolution:energy_crystal>, <draconicevolution:wyvern_energy_core>],[<draconicevolution:energy_crystal>, <rockhounding_chemistry:alloy_items_gems:1>, <draconicevolution:energy_crystal>], [<draconicevolution:wyvern_energy_core>, <draconicevolution:energy_crystal>, <draconicevolution:wyvern_energy_core>]]);
recipes.addShaped(<draconicevolution:wyvern_energy_core>, [[<draconicevolution:draconium_ingot>, <rockhounding_chemistry:alloy_parts:88>, <draconicevolution:draconium_ingot>],[<minecraft:end_crystal>, <draconicevolution:wyvern_core>, <minecraft:end_crystal>], [<draconicevolution:draconium_ingot>, <rockhounding_chemistry:alloy_parts:16>, <draconicevolution:draconium_ingot>]]);
recipes.addShaped(<draconicevolution:wyvern_core>, [[<draconicevolution:draconium_block>, <minecraft:diamond_block>, <draconicevolution:draconium_ingot>],[<rockhounding_chemistry:alloy_parts:28>, <minecraft:end_crystal>, <rockhounding_chemistry:alloy_parts:28>], [<draconicevolution:draconium_ingot>, <minecraft:diamond_block>, <draconicevolution:draconium_block>]]);
recipes.addShaped(<draconicevolution:draconic_core>, [[<draconicevolution:draconium_ingot>, <rockhounding_chemistry:alloy_parts:4>, <draconicevolution:draconium_ingot>],[<minecraft:gold_block>, <minecraft:diamond_block>, <minecraft:gold_block>], [<draconicevolution:draconium_ingot>, <rockhounding_chemistry:alloy_parts:1>, <draconicevolution:draconium_ingot>]]);
recipes.addShaped(<scalinghealth:difficultychanger>, [[<roughtweaks:medikitenchanted>, <scalinghealth:heartcontainer>, <roughtweaks:medikitenchanted>],[<scalinghealth:heartcontainer>, <minecraft:skull:1>, <scalinghealth:heartcontainer>], [<roughtweaks:medikitenchanted>, null, <roughtweaks:medikitenchanted>]]);
recipes.addShaped(<xat:fairy_ring>, [[<minecraft:diamond>, <draconicevolution:draconic_energy_core>, <minecraft:diamond>],[<xat:glowing_ingot>, <avaritia:endest_pearl>, <xat:glowing_ingot>], [<minecraft:diamond>, <draconicevolution:draconic_energy_core>, <minecraft:diamond>]]);
recipes.addShaped(<opencomputers:material:6>, [[<immersiveengineering:material:22>, <appliedenergistics2:material:20>, <immersiveengineering:material:22>],[<ore:nuggetCopper>, <appliedenergistics2:material:11>, <ore:nuggetCopper>], [null, <minecraft:redstone>, null]]);
recipes.addShaped(<opencomputers:material:6>, [[<immersiveengineering:material:22>, <appliedenergistics2:material:20>, <immersiveengineering:material:22>],[<ore:nuggetCopper>, <appliedenergistics2:material:10>, <ore:nuggetCopper>], [null, <minecraft:redstone>, null]]);
mods.immersiveengineering.Crusher.addRecipe(<appliedenergistics2:material:8>, <appliedenergistics2:material:7>, 12800);
mods.immersiveengineering.Crusher.addRecipe(<appliedenergistics2:material:2>, <appliedenergistics2:material:0>, 12800);
//File End
